# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BRCPopUp_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BRCPopUp','~>1.2.0'
  pod 'SnapKit'

  # Pods for BRCPopUp_Swift

end
